### PR TITLE
Bugfix/click outside of modal

### LINKED ISSUE #101: Clicking outside the modal when on import or transcription page, resets all progress to that point
E.g. you are here:

Screen Shot 2022-05-28 at 3 20 42 pm

You then click anywhere outside of the modal. You are returned to the home screen and have to start again (naming project, importing media, etc).

Should instead, either:

1. Show a pop up warning you that you will lose progress if you go back to the home screen, do you want to anyway?

or

2. Just not do anything, the user can click cancel / the X in the corner instead

### PR DESCRIPTION
**Pull request by exquisitebin**
## Click Outside Of Modal -> Asks user whether to confirm cancelling the project

https://user-images.githubusercontent.com/58348527/184081026-d92c7f40-5cf8-4be6-9533-c033987f448c.mp4

<hr/>

### Why is this change needed?
If a user accidently clicks out of the modal, presses cancel, clicks the X or hits 'ESC' they instantly lose all progress in creating their new project. ([Issue#101](https://github.com/chloebrett/mlvet/issues/101))

This update adds a confirmation modal that asks the user whether the user really meant to cancel the new project.

<hr/>

### What did you change?
Added a new component CancelProjectModal which pops up when the main ModalContainer is attempted to be closed.
The projectName is cleared when the project is cancelled.

<hr/>

### OS

- [ ] Linux
- [x] MacOS
- [x] Windows

### CODE REVIEW

**Review by danfeltham — APPROVED** [review]
Wow! Beautifully done, very neat. Thanks for doing this. Approved.

#### Old Bug Discovered
I believe it occurs when you cancel a project that is in the middle of transcribing and start transcribing a new project before the original is finished (even though it is cancelled it may still be running in the background). The result is a hanging transcription that doesn't error, and doesn't complete.

I'll create an issue when the branch is merged.

**Comment by emmapainter** [comment]
Is it okay if I make a UI design for this?

**Comment by exquisitebin** [comment]
> Is it okay if I make a UI design for this?

Sure that sounds all good to me! 
What does this entail out of curiosity? Is this just updating Figma or coming up with a better design?

**Comment by emmapainter** [comment]
> > Is it okay if I make a UI design for this?
> 
> Sure that sounds all good to me! What does this entail out of curiosity? Is this just updating Figma or coming up with a better design?

Yeah I just wanted to play around with what it looks like and Figma is the easiest way for me to do that. Happy to work on it and send you what I end up with or pair with you if you're interested in trying your hand at design 😄

**Review by Irmy — APPROVED** [review]
Not sure if my review is needed still - but all works super smooth on my end too! Love that it prompts at everystage of the onboarding flow - naming project, selecting file and transcription! awesome user feedback

**Comment by emmapainter** [comment]
Can you make it so that if the user is on the new project modal and there is no text in the project name box it just exits without showing the confirm modal?

**Comment by exquisitebin** [comment]
> Can you make it so that if the user is on the new project modal and there is no text in the project name box it just exits without showing the confirm modal?

Yup can do that!

**Comment by exquisitebin** [comment]
> Can you make it so that if the user is on the new project modal and there is no text in the project name box it just exits without showing the confirm modal?

@emmapainter done!

**Review by emmapainter — APPROVED** [review]
Love your work 😄

**Pull request merged**
