### PR TITLE
Feature/word component animation

### PR DESCRIPTION
**Pull request by ghost**
## Summary

Adds some basic animation to words. On playback, selection, hover, etc.

I realise this is not a requested feature. Sorry for going rogue. Happy for you to reject.

Can remove any animation if it looks laggy but I reckon it looks better.

Note: Dragging is broken on develop, not just in this branch. @chloebrett and I are working on this. Will be fixed in another PR.

<hr/>

### Why is this change needed?

More sexy

<hr/>

### What did you change?

I changed the conditional CSS styling for words to be conditional class names. Using class names instead of words means that transitions (animations) could be added.

### After (With Animations)

https://user-images.githubusercontent.com/101784287/187381981-d51149fe-dbde-4702-a625-a0918ccdd995.mp4

### Before (Without)

https://user-images.githubusercontent.com/101784287/187383036-28b0e067-9d72-4ba8-bd4c-8e6ed2355b14.mp4

<hr/>

### OS

- [ ] Linux
- [ ] MacOS
- [x] Windows

### CODE REVIEW

**Comment by chloebrett** [comment]
Can you post a screen recording please

**Comment by ghost** [comment]
> Can you post a screen recording please

Added.

**Comment by chloebrett** [comment]
The word fade-ins mean that fast actions (e.g. selecting quickly, or short words being highlighted for playback) look kind of laggy. We had this fade-in stuff before, I removed it because without it, the app does look a little bit more basic, but it's also way more snappy as a user experience.

**Comment by ghost** [comment]
> The word fade-ins mean that fast actions (e.g. selecting quickly, or short words being highlighted for playback) look kind of laggy. We had this fade-in stuff before, I removed it because without it, the app does look a little bit more basic, but it's also way more snappy as a user experience.

I understand. Again, happy to reject but want to see what others think. Maybe we can add it in the next milestone and set it conditionally (eg: duration > 0.3s then have animation sort of thing - although, not that basic)

**Review by Irmy — CHANGES_REQUESTED** [review]
I prefer the playback fade in on this branch compared to develop currently - I find my engagement as a user during playback is higher with the fade ins. On small words, the highlight is fast on either branch so those small words being barely highlighted is a minor concern for me. We can adjust the threshold more next milestone if needed.

 
However to keep the responsiveness for other editing features can we remove the fade in for onhover on words please - i just found when trying to orientate where my cursor is in the transcription,  I wanted instant UI feedback.  I couldnt tell too much different for drag selecting  multiple words between the two branches but lets keep the develop drag selecting words please :)

**Comment by Irmy** [comment]
If possible can we get this adjusted and merged today? Would love to have the fade ins for playback in the demo for audience engagement

**Comment by ghost** [comment]
Alright closing PR as don't want to distract from more important features

**Pull request closed without merging**
