### PR TITLE
Feature/add menu bar buttons

### PR DESCRIPTION
**Pull request by jhea0008**
## Summary

Adds more buttons to the project page, specifically undo, redo, delete, cut, copy and paste.
Also adds a change  so that clicking items in the menu bar does not affect the current selection. 

<hr/>

### Why is this change needed?
Usability and discoverability
<hr/>

### What did you change?
New buttons are purely a UI change. The buttons use the same functions as the keyboard shortcuts do
<hr/>

### Does it depend on any other changes/PRs?

I have pulled the isEventInElement function from @Taz17 's branch take-video-preview so that may conflict

<hr/>

### Screenshots of UI changes, if any
Screen Shot 2022-10-13 at 12 56 08

<hr/>

### OS

- [ ] Linux
- [X] MacOS
- [ ] Windows

### CODE REVIEW

**Review by chloebrett — APPROVED** [review]
Code looks good

**Comment by MutazAshhab** [comment]
This is amazing Justin, I tested it out and functionality is 100% correct. I did notice two things.

1. Clock, seek, and play button are no longer centered. @rileykeane @emmapainter designs?
2. Right now if you hover over the icons you dont get text describing the functionality which icon does.

Example: I am hover one of the inputs in Future Supers' join form:

image


You can find more info about title property here: https://www.computerhope.com/issues/ch001076.htm#:~:text=Unlike%20the%20Microsoft%20Internet%20Explorer,text%20for%20images%20that%20do.

[Set custom text for material icon](https://stackoverflow.com/questions/69683574/set-custom-text-for-material-icon)

^^ Forget this... here is how to do it:

image

**Review by emmapainter — CHANGES_REQUESTED** [review]
Looking at this now I definitely think the icons should be grey (same grey as used for the seek icons). Maybe play can stay as yellow but the rest should be grey (including home and feedback), they pull too much attention when they're all yellow. 

Agree with Mutaz that tooltips seem pretty necessary now that we have so many buttons, although I'm not fussed if you do that in this PR or merge this and raise another PR with tooltips. Ideally the tooltips would look like the designs on Figma (screenshot from Figma attached).
Screen Shot 2022-10-13 at 3 03 03 pm

**Review by MutazAshhab — APPROVED** [review]

**Comment by jhea0008** [comment]
Screen Shot 2022-10-13 at 18 13 50
@emmapainter not sure if this looks better but it's now been updated to this

**Comment by jhea0008** [comment]
Screen Shot 2022-10-13 at 19 23 23
Here are the tool tips for now

**Review by Irmy — APPROVED** [review]
Looks dope!

**Comment by chloebrett** [comment]
Could we use the MUI tooltips instead of native ones? Little bit nicer UI and I think we use them elsewhere already

https://mui.com/material-ui/react-tooltip/

**Review by emmapainter — APPROVED** [review]
Looks good, thanks for changing the colours

**Pull request merged**
