### PR TITLE
MLVET v0.02 beta 

### PR DESCRIPTION
**Pull request by rileykeane**
Merging the latest develop into UAT. 

This version will be used in the demo and launched as the beta on Friday. 🎉

Can everyone please try packaging the app and running it and let me know if there are any issues?

<hr/>

### OS

- [x] Linux
- [x] MacOS
- [ ] Windows

### CODE REVIEW

**Review by MutazAshhab — APPROVED** [review]
Works as expected on Linux, however, the name of the app is MLVET-0.0.1 instead of MLVET-0.0.2

**Review by Irmy — CHANGES_REQUESTED** [review]
Packaged on windows - tested all shortcuts, video resizing, scrubber bar, drag word, saving of project. API key flow worked well. 

Only 1 issue found - UI crashing when word is pasted and undone via shortcut at the end of the transcription and word is not unselected beforehand. If i click elsewhere in the UI after pasting and then undo its fine, but if i do not and then undo, it crashes and entire app needs to be closed down again

**Review by Irmy — APPROVED** [review]
An issue is open for the bug i mentioned so understandable to merge to UAT given demo is tomorrow so changing my review to approve given time constraints

**Review by ghost — CHANGES_REQUESTED** [review]
Change the version in the package.json to be '0.0.2'

**Review by ghost — APPROVED** [review]
Added version 0.0.2

**Comment by ghost** [comment]
> 

Should be fixed now. Version 0.0.2

**Pull request merged**
