### PR TITLE
Cloud config cherry pick

### PR DESCRIPTION
**Pull request by chloebrett**
# Cloud Config File

## Description
Implements the ability to enter, store and retrieve API keys nad a default TranscriptionEngine. Configs are stored in a JSON file in the appdata mlvet folder as "cloudConfig.json". 

The currently stored key is displayed in the CloudConfigView text box upon opening.
The text for the CloudConfigView information changes depending on whether it is the user's first time entering the API key.

## Why is this change needed?
Allows users to enter their custom API key, use it to transcribe and have it saved for multiple sessions.

## OS

- [x] Windows
- [x] Mac
- [ ] Linux

### CODE REVIEW

**Review by exquisitebin — APPROVED** [review]
Awesome thanks for helping fix my branch! It seems to be all working.

**Review by manikag-12 — CHANGES_REQUESTED** [review]
Look really good but when when there already is a key saved and I create a new project, it doesn't let me move forward without changing the transcription key.

The save button is disabled and that's the only way to move to the next view

image

**Comment by MutazAshhab** [comment]
I've tested it out locally, it works and I found a couple of things.

1. If you add an api key, click save (go to the next view), then go back, it save button is then disabled. It should be enabled as the api key entered by the user is persisted.
2. The back and save button in the cloud config view and not longer on the same level as the next view. See this video


https://user-images.githubusercontent.com/86769131/187671070-0cb218a1-1ed9-421d-be07-cf837fabb8ec.mp4

**Comment by exquisitebin** [comment]
> Look really good but when when there already is a key saved and I create a new project, it doesn't let me move forward without changing the transcription key.
> 
> The save button is disabled and that's the only way to move to the next view
> 
> image

New commit should fix this issue

**Review by rileykeane — CHANGES_REQUESTED** [review]
@exquisitebin @Taz17 @chloebrett  It looks like you can't paste the key into the text field - which is a huge pain to have to type it out...

I believe it's because we have custom copy/paste actions. How difficult is this going to be to fix?

**Comment by rileykeane** [comment]
Also - the screen to enter a key should not appear in the new project flow if the user has already provided a key.

**Comment by exquisitebin** [comment]
> I've tested it out locally, it works and I found a couple of things.
> 
> 1. If you add an api key, click save (go to the next view), then go back, it save button is then disabled. It should be enabled as the api key entered by the user is persisted.
> 2. The back and save button in the cloud config view and not longer on the same level as the next view. See this video
> 
>  misalignment.mp4

New commits should fix both issues

**Comment by exquisitebin** [comment]
> @exquisitebin @Taz17 @chloebrett It looks like you can't paste the key into the text field - which is a huge pain to have to type it out...
> 
> I believe it's because we have custom copy/paste actions. How difficult is this going to be to fix?

Chloe and I found it's a Mac problem, as it works fine on my Windows.



> Also - the screen to enter a key should not appear in the new project flow if the user has already provided a key.

The current issue is that its managed by the useEffect in the ModalContainer which only gets called once while you're at the home page. Therefore if you complete making a new project and go back to the homepage (or restart the app) it no longer appears.

**Review by rileykeane — APPROVED** [review]

**Review by manikag-12 — APPROVED** [review]

**Pull request merged**
