### PR TITLE
Selection UI improvements

### LINKED ISSUE #185: Selected words should not have visual gaps between them
Make the spaces be absorbed into the selection UI so the selection is a continuous rectangle (at least within a single line)

### PR DESCRIPTION
**Pull request by chloebrett**
Resolves #185 

Continuous highlight, blue selection, round ends, etc - closer to descript UI, our own UI designs, and just closer to something nice to use in general.

Also, changed the cursor to the text select one.

Out of scope for this: performance of selection/highlight - it's not terrible but could be improved

Also taking Riley's suggestion of using a more standard blue colour for the highlight, so that the orange 'currently playing' marker stands out more, and so that the user is not swamped with yellow.

Feel free to provide feedback on both implementation and looks - will clean up a bit and post screenshots tomorrow

### CODE REVIEW

**Comment by chloebrett** [comment]
Basic screenshot

**Comment by chloebrett** [comment]
Basic screenshot

Screen Shot 2022-08-25 at 11 01 33 pm

**Comment by Irmy** [comment]
These improvements make a huge impact on the UI! It looks so good - are we able to include the delete makers in the continuous highlight please? i really like the rounded corners of the highlight blue - can we translate that to the yellow playback aswell. Happy for @rileykeane  and @emmapainter  to add in their UI perspectives here
image

**Comment by Irmy** [comment]
Do we have the ability to change the on hover blue highlight to rounded corners as well? Just saw the on hover and drag select UI is a bit different - on hover square corners and drag select is round

**Comment by chloebrett** [comment]
I thought the delete marker interrupting the highlight looked alright but on second thought it makes more sense to keep it continuous - will do.

Yellow playback I can make rounded but ultimately want to change this to a little playback marker (like a cursor between words or something, similar to how video editors do it) since the UX of the playback marker is a bit meh overall.

On hover highlight with corners makes sense too - will do!

Checklist, will update as I do them:

- [x] Edit marker continuous highlight
- [x] Playback highlight rounded corners
- [x] Hover select rounded corners

**Review by Irmy — APPROVED** [review]
Love it - looks great! The cursor helps alot 
image

**Review by rileykeane — APPROVED** [review]
Very nice! Thanks for getting this one done.

**Pull request merged**
