### PR TITLE
Feature/new shortcuts

### LINKED ISSUE #146: Spacebar to play/pause doesn't work when there is an active selection

### LINKED ISSUE #242: Out of sync video playback/scrubber bar/ transcription playback - spacebar triggered
When you click on the video and press spacebar this only causes the video to  start playing and the scrubber bar and transcription playback to not do anything. When you press play on the UI then, all 3 are out of sync
Uploading MLVET 2022-08-31 14-33-02.mp4…

### LINKED ISSUE #343: Video preview shortcuts are now missing.
After the revert happened, you can no longer seek forward/backward using the arrow keys.

If you do any work on this or use another OS, then please check the boxes below to update what works and what doesnt

### Linux
- [x] Space to play/pause
- [ ] Seek forward using right arrow key
- [ ] Seek backward using left arrow key

### Mac OS
- [ ] Space to play/pause
- [ ] Seek forward using right arrow key
- [ ] Seek backward using left arrow key

### Windows
- [x] Space to play/pause
- [x] Seek forward using right arrow key
- [x] Seek backward using left arrow key

### PR DESCRIPTION
**Pull request by v1ta1287**
## Summary

Small PR to add video preview shortcuts for pausing/playing, seeking forward and seeking back.
<hr/>

### Why is this change needed?
Had to re-add shortcuts after playback redux got removed
<hr/>

### What did you change?
- useKeypress calls in PlaybackManager.tsx 
- Changed useKeypress so that it uses keydown rather than keypress
<hr/>

### Does it depend on any other changes/PRs?

<hr/>

### Screenshots of UI changes, if any

<hr/>

### Explain things which the reviewers are likely to need explaining. Remember that they didn’t write the code.

<hr/>

### Testing details if applicable

<hr/>

### Any sections in particular you want reviewed/discussed

<hr/>

### Links to any design documents which you made/used in order to make the decisions that you made.

<hr/>

### OS

- [ ] Linux
- [ ] MacOS
- [x] Windows

### CODE REVIEW

**Comment by MutazAshhab** [comment]
Why did you change `keypress` to `keydown`?

Did you also test the other parts of the app which use keypress? I'll test it soon

**Comment by v1ta1287** [comment]
The `keypress` event is only fired for keys that produce a character value, whereas `keydown` is fired for all keys. Thus I had to change it so that left/right arrow keys could work. I haven't done extensive testing on the other features which used `keypress`, but `keydown` should work for everything keypress works for.

**Comment by Mhudlark** [comment]
Tagging @fwan0018 and @emmapainter for mac testing and @Irmy for PM approval

**Review by fwang1703 — APPROVED** [review]
Code looks good and working on Mac!

**Review by Irmy — APPROVED** [review]
Works great on windows!! 
Just go through the shortcut git issues and see which one you can close down because alot related to similar things :) Im sure there will be a few to close at once

**Review by MutazAshhab — APPROVED** [review]

**Pull request merged**
