### PR TITLE
Feature/merge split words

### PR DESCRIPTION
**Pull request by chloebrett**
~~Depends on #182~~

Use cases
1. The transcription inaccurately transcribes what should be one word, as two separate words (e.g. "depend" gets transcribed incorrectly as "deep end")
2. The opposite happens e.g. "deep end" gets incorrectly transcribed as "depend"

User perspective - merging two+ words into one
1. Merge the words (cmd/ctrl + L)
2. Double-click the merged words to correct the text (e.g. "deep end" -> "depend") (this PR: https://github.com/chloebrett/mlvet/pull/178)

User perspective - splitting one word into two+
1. Double-click the words to correct the text (e.g. "depend -> deep end" (this PR: https://github.com/chloebrett/mlvet/pull/178)
2. Split the words (cmd/ctrl + shift + L)

Currently, just for this PR, correcting words isn't supported -> therefore, test functionality by merging two words together and then splitting them to see how it works.

Features
- Cmd / ctrl + L merges two or more words together, so that they can be manipulated as one (and, once https://github.com/chloebrett/mlvet/pull/178 is ready, then correcting the merged word)
- Cmd / ctrl + shift + L splits words
- Undo fully supported
- Buffers work in a sane way
- Selection after actions, undos and redos works in a sane way

Notes
- Was originally going to do Ctrl + M for merging and Ctrl+Shift+M for unmerging, but this is reserved for minimising windows on mac
- In all likelihood the keyboard shortcut might not work on win/linux, let me know and I'll fix it as part of https://github.com/chloebrett/mlvet/issues/180

Demo

https://user-images.githubusercontent.com/6735055/185527148-1d0c429b-47fd-46c2-95f8-995750859048.mov

### CODE REVIEW

**Comment by chloebrett** [comment]
Almost ready for review, just need to add screenshots, fix selection logic after actions and undos, and clean up a bit

**Comment by chloebrett** [comment]
Getting very close, just need to make the buttons enable/disable themselves depending on the current selection

**Comment by chloebrett** [comment]
Ready for review!

**Comment by Irmy** [comment]
Looks good - works for windows for me at least

**Comment by MutazAshhab** [comment]
`ctrl + L` and `ctrl + shift + L` works on linux :tada:

**Review by MutazAshhab — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
