### PR TITLE
Bugfix/center vid preview

### LINKED ISSUE #126: Uneven black bars on video preview
Screen Shot 2022-05-31 at 12 56 44 PM

### PR DESCRIPTION
**Pull request by ghost**
## Summary

This PR fixes [this issue](https://github.com/chloebrett/mlvet/issues/126) and makes the video preview resizable using the divider / slider in the center of the project page.

<hr/>

### What did you change?

I added a resize slider component which can be used to resize the video preview container in the project page.

I added a package which is basically a single debouncer react hook. Look up debouncers if you don't understand what they are. Useful knowledge. I used a debouncer here to avoid hundreds of state changes (each resize event)

<hr/>

###  To test

Try it out in the app! :)

### CODE REVIEW

**Comment by chloebrett** [comment]
The centering seems to work which is nice! However the resizing doesn't work on my machine

Also curious if you've put minimum sizes for each half so that the video preview doesn't end up e.g. 1% of the width if the user drags all the way to the right?

https://user-images.githubusercontent.com/6735055/182594637-b5b31632-1924-4b8e-97f4-90604921f9f3.mov

**Comment by chloebrett** [comment]
Still not working on my machine

https://user-images.githubusercontent.com/6735055/182834763-b69ad389-2c87-4b79-8727-2eae257dcbe0.mov

**Review by rileykeane — CHANGES_REQUESTED** [review]
The UX is not too hot hot on Mac. The resize slider is hard too garb and keep a hold on. When you do manage to resize it, its quite choppy.

Tested on a 2021 Macbook Pro (M1 Pro)

https://drive.google.com/file/d/1l26EGF5d5t0-OgUX_UMPg3fKeXDwNxwa/view?usp=sharing

**Review by danfeltham — APPROVED** [review]
Looks really neat.

Only feedback I have is that from a usability point of view it isn't intuitive that the functionality exists the draw/resize the transcription/video preview section divider.

Possible Bug: When I drag on my computer, the divider doesn't follow the cursor exactly. It seems to move at only half the disance travelled by the cursor. I've attached a video

https://user-images.githubusercontent.com/41976158/182990713-ba905102-d2d5-405b-894a-5fca6684de24.mp4

**Comment by ghost** [comment]
@chloebrett @rileykeane @Aretle @manikag-12

I have updated the functionality to use `onmouse` events instead of `ondrag`. Additionally some of the listeners have been moved onto the `body` for better drag experience

Unfortunately the min and max width calculations require manual values for calculation in order to work on all screen sizes. This is because we use a mix of JS and CSS for styling :(

Please have another look when you have a chance :)

@Aretle in regards to your comment about it not being intuitive in the middle - I understand. I originally had it the other way where the user resizes the video preview itself but found it to be quite hidden. I added the highlight to draw attention to the interactivity. Happy to change in the future though :)

**Comment by hhen0005** [comment]
@Aretle

**Review by chloebrett — APPROVED** [review]
Generally, it works - enough that I'm happy to approve. There are some issues when the screen is set to a particularly small width. Also, the maximum preview size is pretty small when on a large screen (e.g. 2560x1440). Please make issues out of these if you merge before resolving :)

Small width: Screen Shot 2022-08-08 at 1 05 47 pm

Large screen: Screen Shot 2022-08-08 at 1 06 30 pm

**Comment by ghost** [comment]
Looks like there's an issue. Occurs when the user resizes the page. When the user resizes, the page width doesn't get updated so the video preview resizer doesn't know it can get bigger.
I will create an issue for it.
https://github.com/chloebrett/mlvet/issues/172

**Review by rileykeane — APPROVED** [review]
Small issue that has already been raised in #172. It's not major so I think we are fine to proceed. 

Sometimes it can be a little fiddly with a trackpad on mac - but for the most part works really well.

**Pull request merged**
